package password.vault.api;

public enum ServerResponses {
    UNKNOWN_COMMAND(),
    WRONG_COMMAND_NUMBER_OF_ARGUMENTS(),
    WRONG_COMMAND_ARGUMENT(),
    SESSION_EXPIRED(),
    DISCONNECTED(),

    NOT_LOGGED_IN(),
    ALREADY_LOGGED_IN(),

    REGISTRATION_SUCCESS(),
    REGISTRATION_ERROR(),

    LOGIN_SUCCESS(),
    LOGIN_ERROR(),

    LOGOUT_SUCCESS(),
    LOGOUT_ERROR(),

    CREDENTIAL_ADDITION_SUCCESS(),
    CREDENTIAL_ADDITION_ERROR(),
    UNSAFE_PASSWORD(),

    CREDENTIAL_REMOVAL_SUCCESS(),
    CREDENTIAL_REMOVAL_ERROR(),

    CREDENTIAL_RETRIEVAL_SUCCESS(),
    CREDENTIAL_RETRIEVAL_ERROR(),

    PASSWORD_SAFETY_SERVICE_ERROR(),

    CREDENTIAL_GENERATION_SUCCESS(),
    CREDENTIAL_GENERATION_ERROR(),

    PASSWORD_GENERATION_ERROR(),

    USER_ALREADY_LOGGED(),
    USER_NOT_LOGGED_IN(),
    PASSWORD_DO_NOT_MATCH(),
    NO_SUCH_CREDENTIAL(),
    NO_CREDENTIALS_ADDED(),
    HELP_COMMAND(),
    USER_DOES_NOT_EXIST(),
    SAFE_PASSWORD();

    ServerResponses() {
    }
}
